# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build with

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build_linux:
    name: linux
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar_linux
        path: build/libs/*.jar  
  
  build_mac:
    name: mac OS
    
    needs: build_linux
    
    runs-on: 	macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar_mac
        path: build/libs/*.jar
        
  build_windows:
    name: windows
    
    needs: build_mac
    
    runs-on: 	windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar_windows
        path: build/libs/*.jar
